### ISSUE TITLE
Inconsistent "last updated"

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#12]
For example, SCC web shows that for https://github.com/oeg-upm/webODE the last update is 11/2021, but it has not been contributed to in the last 4 years.

**Comment by dakixr** [comment]
The output that I get from SOMEF:

```
"dateModified": {
        "excerpt": "2021-11-26T17:40:05Z",
        "confidence": [
            1.0
        ],
        "technique": "GitHub API"
    }

```
However, as you mentioned above this repo hasn't been updated in the last 4 years.

<img width="909" alt="Screenshot 2022-03-29 at 16 12 40" src="https://user-images.githubusercontent.com/26521823/160631317-5278a125-cf39-4239-af9b-8220769d6463.png">

Is this an error from SOMEF or could just be that the description has been updated more recently?

**Comment by dgarijo** [comment]
Maybe it's because of that...
