### ISSUE TITLE
Some "Ontology" Pages are not ontologies.

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#20]
For example:
- https://github.com/oeg-upm/r2rml-editor does not have anything, yet it's classified as an ontology.
- https://github.com/oeg-upm/docker-geokettle-x3geo

Please double check these

**Comment by dakixr** [comment]
This issue will be addressed with the next release of SOMEF. 
Using the 'isOntology' or similar field.

**Comment by dakixr** [comment]
This is addressed in the latest pull-request
