### ISSUE TITLE
Error in repo

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#25]
In Morph-OME, somef detects the logo: 
https://raw.githubusercontent.com/oeg-upm/Morph-OME/master/static/logo-min.png

But SCC does not show it. Why?

**Comment by dakixr** [comment]
![Screenshot 2022-03-27 at 18 03 49](https://user-images.githubusercontent.com/26521823/160290197-6756decc-0827-4e36-ba83-0e48a937aff2.png)
