### ISSUE TITLE
Repo looks incorrect

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#29]
The repo below seems like is derived from the pits of hell:
![Uploading Screenshot from 2022-03-28 13-05-37.png…]()

**Comment by dgarijo** [comment]
![Screenshot from 2022-03-28 13-05-37](https://user-images.githubusercontent.com/1520666/160385551-84f06d51-0441-4fe6-9baa-79858e0d06c8.png)

**Comment by dakixr** [comment]
It should be a cache problem or you just visualized a 'dev-preview' of SCC example
![card](https://user-images.githubusercontent.com/26521823/160627512-b6266e3d-d978-4839-b15f-38605a86d904.png)

**Comment by dgarijo** [comment]
Not a cache problem: it fails in Firefox. In Chrome it can be seen fine

**Comment by dakixr** [comment]
True. I'll look into it
