### ISSUE TITLE
Documentation: what does "updated recently" mean?

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#37]
I know this is something like less than 3 months. Is this correct?

**Comment by dakixr** [comment]
I changed the about page to this:

<img width="283" alt="Screenshot 2022-04-28 at 19 47 00" src="https://user-images.githubusercontent.com/26521823/165815484-2b732146-cf6a-4243-a7d9-911eb9f4d90a.png">

**Comment by dgarijo** [comment]
Perfect
