### ISSUE TITLE
Logs for each repo are not shown

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#40]
It is unclear what the status of each repository is.

Somef produces a log, but we don't see it or know where it is in scc.

The log should be accessible

**Comment by dakixr** [comment]
What do you mean by this? 
When running `scc extract <repos.csv>`; do you want to see all the SOMEF output?

**Comment by dgarijo** [comment]
I would like to know the full somef output, yes. Just in case something goes wrong. Maybe it could be made optional under a --vervose command or similar
