### ISSUE TITLE
Improve status descriptions

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#47]
The descriptions are not great. They don't render very good. It would be nice to have some post processing.

**Comment by dakixr** [comment]
This is the new format:

<img width="660" alt="Screenshot 2022-04-28 at 21 11 41" src="https://user-images.githubusercontent.com/26521823/165828475-08041762-a4fb-46d4-a8fe-51fac2df8541.png">

**Comment by dgarijo** [comment]
Awesome
