### ISSUE TITLE
SCC does not process all repos of an organization

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#5]
I was looking at morph-kgc and it does not appear
@dakixr, any explanation why?

**Comment by dakixr** [comment]
Hi, I am using a subset of all the repos of oeg-upm just for time saving reasons. However, currently I am extracting metadata for all repos to update the demo page.

Besides that, it's true that somef dies when executed on some repos. Once I'm finished running this iteration I'll provide a list with the repos that failed.

Daniel Rodríguez Mariblanca

**Comment by dgarijo** [comment]
Excellent, we need that list to improve the tool :)
I tested somef out with the repo above and it works, so I understand it's not part of the initial subset.

**Comment by dgarijo** [comment]
I'll close the issue for now
