### ISSUE TITLE
Paths from "usage" have absolute paths

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#50]
For example, for morph OME, I get:

```
Usage
How to use it

python /Users/dakixr/Desktop/github/scc/tmp-data/metadata/oeg-upm/Morph-OME/app.py
```

This is almost correct, but I would like the path to be:
```
python oeg-upm/Morph-OME/app.py
```
I.e., start from the organization name

**Comment by dakixr** [comment]
New look:

![Screenshot 2022-04-30 at 19 06 54](https://user-images.githubusercontent.com/26521823/166115351-1ef39d3e-1f18-49c3-ba85-2956c6caf423.png)

Do I add the org name or could it be misleading?

**Comment by dgarijo** [comment]
Ah, I understand your point. I think you are right, your proposal is better.

**Comment by dgarijo** [comment]
So do NOT add the org name.
