### ISSUE TITLE
Double header if no usage instructions are found, but it's a Python package

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/scc#51]
See the screenshot below
![Screenshot from 2022-04-29 18-40-57](https://user-images.githubusercontent.com/1520666/165987393-f43f9d0a-9a73-4298-918b-9be7a1b0b4d7.png)

In this case, it should only show "How to use it"

**Comment by dakixr** [comment]
Agree, new look:

![Screenshot 2022-04-30 at 19 09 28](https://user-images.githubusercontent.com/26521823/166115441-e21e1253-f1b7-46d3-8299-1f73e1efab7d.png)
