### ISSUE TITLE
Application crashes when it doesn't find a repo

### ISSUE THREAD

**Issue by esgg** [oeg-upm/scc#52]
The command scc extract crashes when it doesn't find a repo:

FileNotFoundError: [Errno 2] No such file or directory: '/home/XXXXXX/oeg-upm_metadata/Jarsomatic'
Extracting metadata from https://github.com/oeg-upm/Jarsomatic

Previous to this error, another exception occurred:
Traceback (most recent call last):
  File "/home/egonzalez/scc/src/scc/commands/extract_metadata.py", line 49, in fetch
    metadata["inspect4py"]["run"] = ins4py["software_invocation"][0]["run"]
KeyError: 'run'

The problem shows up when we run scc with the option ins4py.

**Comment by dgarijo** [comment]
It may be an inspect4py derived error, bit SCC should be robust against this

**Comment by dakixr** [comment]
This issue has been addressed in the last PR:

```
❯ scc extract --inspect4py -i https://github.com/oeg-upm/Jarsomatic -o .
It may take a while... Depends on repository size and Github API limitations.
Extracting metadata from https://github.com/oeg-upm/Jarsomatic
ERROR: Could not run inspect4py for https://github.com/oeg-upm/Jarsomatic: Error in sowftware_type software_invocation
100% (1 of 1) |####################################################################################################################| Elapsed Time: 0:00:04 Time:  0:00:04
ERROR: inspect4py could not be ran in the following repo/s:
https://github.com/oeg-upm/Jarsomatic

✅ Successfully extracted metadata from (1/1) repositories.
```
